### PR TITLE
FileHandler Changed to Using Accessors

### PR DESCRIPTION
**Pull request by osbornjd**
In conjunction with the recommendation from [PR 408](https://github.com/eclipse/ice/pull/408), this PR changes the design of the FileHandler slightly to use default constructors and then set the source and destination files via accessors, rather than setting them in the constructor.

This [commit](https://github.com/eclipse/ice/pull/410/commits/7f4e4f559ed62f3eb633c9b67964fc0fc07de354) also addresses the bug pointed out by @jayjaybillings in issue [409](https://github.com/eclipse/ice/issues/409).

There is also a commit that adds two example files that demonstrate how the commands API works for the user.

### CODE REVIEW

**Comment by jayjaybillings** [comment]
@osbornjd can you resolve the merge conflict please? I think you need to pull the latest from ICE and then merge that into your code.

I believe the conflict is that I changed the name of a class and function.

**Comment by osbornjd** [comment]
@jayjaybillings I believe this is ready to be reviewed now.

One comment on the previous commit - I moved the instantiation of the LocalMoveFileCommand (as well as copy) into setMoveConfiguration (or copy) instead of in the constructor of the LocalFileHandler. I think this is much cleaner because it allows the base class to have a single Command member variable which is then instantiated depending on what the user calls.

If the creation of the command is left in the constructor, it requires you to have two member variables CopyFileCommand and MoveFileCommand and basically you need a separate track of code to deal with each of the copy/move logic flows. This is not ideal since all of the logic is nearly identical, so it is highly desired to have a single Command member variable to reduce the amount of code in the classes.

The saving is that in LocalFileHandler we have two (nearly identical) setConfiguration functions, whereas if we have the creation in the constructor of the LocalFileHandler we need to have 4 nearly identical functions.

**Comment by osbornjd** [comment]
I left these blank because the OS is set by default now - I suppose I should have added them back in to the tests for demonstration purposes. 

But adding in || commandConfig.getOS() == null back into Command seems not useful since it is now set by default in the constructor, so that will always pass.

**Comment by jayjaybillings** [comment]
This looks good. It appears to have addressed all of my change requests and then some. All checks pass and @osbornjd is covered under the UT-Battelle MLA.

**Pull request merged**
