### PR TITLE
Initial Commands API 

### PR DESCRIPTION
**Pull request by osbornjd**
This PR introduces a basic class structure for the Commands API, which is being rewritten as discussed in [issue 384](https://github.com/eclipse/ice/issues/384).

### CODE REVIEW

**Comment by jayjaybillings** [comment]
@osbornjd Can you amend your last commit to sign it off please? You can do this by 
```bash
git commit --amend --signoff
```
That should fix the validation error above.

**Comment by osbornjd** [comment]
@jayjaybillings I'm not sure why but I did as you suggested, wrote the commit in VI, and the commit message hasn't changed

**Comment by jayjaybillings** [comment]
I'm rerunning the validation check now.

**Comment by jayjaybillings** [comment]
Did you push your change?

**Comment by osbornjd** [comment]
There now I did, for some reason it wouldn't let me push in terminal so I just added a new line to one of the files and pushed in eclipse

**Comment by jayjaybillings** [comment]
I think you will need to specifically amend that commit with a rebase. See here:

https://help.github.com/en/articles/changing-a-commit-message

**Comment by jayjaybillings** [comment]
All checks pass. It was easy enough to merge the changes. The total number of additions is well below the contribution limit that requires a CQ, but @osbornjd is covered under ORNL's MLA anyway. Accepted. Thanks!

Congrats on your first commit to the Eclipse ICE repo!

**Pull request merged**
