### PR TITLE
Bug 479223 Added extension and extension points

### PR DESCRIPTION
**Pull request by wo-amlangwang**
Added extension points about:
IMasterApplicationFactory
IVizService
IWorkbranch
IParaViewProxyBUilder
IParaViewProxyFactory
Added some extension

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=479223

**Comment by jayjaybillings** [comment]
There are two problems with this. I would like to ask @waynebeaton to share his wisdom on why the ip-validation fails since you have a valid CLA. Wayne, any thoughts?

The second problem is that your launch configuration, ICE Build - Clean and Install.launch, has not been properly merged. Please fixed the ">>>>> HEAD" type lines because they are merge errors.

**Comment by jayjaybillings** [comment]
The problem is here:

<<<<<<< HEAD
<mapEntry key="DYLD_LIBRARY_PATH" value="/Users/superlangwang/HDFJava/lib"/>
=======
 <mapEntry key="LD_LIBRARY_PATH" value="/home/bkj/Programs/hdf-java-2.10/HDF-JAVA-2.10.0-Linux/usr/lib/"/>		 <mapEntry key="LD_LIBRARY_PATH" value="/home/bkj/Programs/hdf-java-2.10/HDF-JAVA-2.10.0-Linux/usr/lib/"/>
>>>>>>> refs/remotes/ICE/jay/projectSupport

Just get rid of the three lines that are not XML and this will be fine.

**Comment by jayjaybillings** [comment]
I spoke with @waynebeaton and he found the problem. Your *first* commit is missing a signed-off-by statement and that is what is causing the problem with the IP validation. 

@waynebeaton said that we can still accept this pull request. However, please make sure in the future that *all* of your commits have signed-off-by statements on them. We really need to see it on every commit that you make. 

As soon as you fix your launch file (see my comment above) I will merge this.

**Comment by jayjaybillings** [comment]
I haven't forgotten about this. I'll pull it as soon as a I have time since I was busy at EclipseCon Europe last week.

**Comment by jayjaybillings** [comment]
Looks fixed. Thanks. Merging this since @waynebeaton said it was OK to accept it, you fixed the merge error and it is less than 1000 lines.

**Pull request merged**
