### PR TITLE
January initial contribution cleanup

### PR DESCRIPTION
**Pull request by jonahkichwacoders**
This pull request contains whitespace and copyright cleanup that will be fed into January initial contribution.

### CODE REVIEW

**Comment by jayjaybillings** [comment]
This will most likely have to go through IP review. I'll let you know.

**Comment by jonahkichwacoders** [comment]
OK, for the review it may be helpful to add these stats showing that excluding EOL changes, there is only 101 insertions.

$ git diff --shortstat jonah/january_copyright_cleanup..origin/jay/january 
 108 files changed, 2257 insertions(+), 2387 deletions(-)

$ git diff --ignore-space-at-eol --shortstat jonah/january_copyright_cleanup..origin/jay/january 
 108 files changed, 101 insertions(+), 231 deletions(-)

**Comment by jayjaybillings** [comment]
According to @waynebeaton line endings don't count. In this case, there are only about 100 other insertions.

**Comment by jayjaybillings** [comment]
Accepted. Thanks!

**Pull request merged**
