### PR TITLE
Add UI code for the appstore

### PR DESCRIPTION
**Pull request by anarak**
The code in this PR is "as-is", will need refactoring and proper alignment/styling of components.

Signed-off-by: Anara Kozhokanova anara.ornl@gmail.com

### CODE REVIEW

**Comment by SmithRWORNL** [comment]
@anarak The IP validation for this pull request failed because these commits don't have the "signed off by" message on them. You should have this message on all commits for Eclipse projects. You can set your Eclipse up to automatically apply this statement with a single button press. 

Go to Windows -> Preferences, then Team -> Git -> Configuration and make sure you have a "user" key with "email" and "name" nodes. The name and email should match the ones for the account you used to accept the CLA. Then, in the git perspective, in the upper right of the Commit Message box is a button that will automatically apply the signed off statement to your message. 

Please make sure that you do this for all future commits.

**Comment by anarak** [comment]
Thanks @SmithRWORNL, I saw that IP validation failed because of signing off. So, does that mean that my old commits won't pass that validation?

**Comment by anarak** [comment]
I rebased all previous commits so that they have my signature. but it seems validation is still failing. Now, I wonder if a new PR should be created and this one closed instead?

**Comment by SmithRWORNL** [comment]
@anarak Yes, it looks to me like the validation should be passing now, so I would try opening a new PR.

**Comment by anarak** [comment]
Closing this one and will create a new PR.

**Pull request closed without merging**
