### PR TITLE
Bug 471356 : Added example of connecting to and using ParaViewWeb service.

### PR DESCRIPTION
**Pull request by scottwittenburg**
Bug 471356

Signed-off-by: Scott Wittenburg <scott.wittenburg@kitware.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471356

**Comment by jayjaybillings** [comment]
I was reviewing the code here an noticed that the by-line lists Jordan and Sebastien as the authors and not you. Jordan is already an ICE committer, so there is no problem there. However, just for the provenance record, will you please certify that you are Sebastien's co-worker and that you are submitting this on behalf of him and Kitware Inc, at my request, because he is on vacation?

**Comment by scottwittenburg** [comment]
Sure, how do I do that?

**Comment by scottwittenburg** [comment]
Yes, Sebastien Jourdain and I are both employed by Kitware Inc. and I am submitting this on his behalf, at your request during our meeting a few weeks ago, while he is on vacation.

**Comment by jayjaybillings** [comment]
Awesome, thanks for clarifying that for the record. I will accept this contribution since it is less than 1000 lines, directly addresses our bug, and you have a signed CLA.

**Pull request merged**
