### PR TITLE
Changed the message string for connection error in VizConnection

### PR DESCRIPTION
**Pull request by kburova**
Signed-off-by: Ksenia Burova <kburova@vols.utk.edu>

### CODE REVIEW

**Comment by kburova** [comment]
Outputs corrects path in 'Visualization Fail' error message depending on operating system

**Comment by jayjaybillings** [comment]
Thanks very much for making this change. Can you please tell me the bug number that tracks this work?

**Comment by kburova** [comment]
480697

**Comment by jayjaybillings** [comment]
Where is that bug located? Bugzilla or GitHub? Put a link please.

**Comment by kburova** [comment]
Sorry!  **Bugzilla:** https://bugs.eclipse.org/bugs/show_bug.cgi?id=480697

**Comment by jayjaybillings** [comment]
Accepted. Thanks very much!

**Pull request merged**
