### PR TITLE
Bug 481365 IMasterDetailsPageProvider

### PR DESCRIPTION
**Pull request by menghanli**
Created IMasterDetailsPageProvider interface and extension point 
Added default implementation and extension

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=481365

**Comment by jayjaybillings** [comment]
Great work Menghan!

Unfortunately, I cannot accept this pull request at the moment because it is too large. The problem is cause by the userMatDB.xml file. 

Please replace the contents of your userMatDB.xml in org.eclipse.ice.materials/data with the contents from:

https://github.com/eclipse/ice/blob/jay/UIRefactor/org.eclipse.ice.materials/data/userMatDB.xml

After that, commit and push and this should go away.

**Comment by jayjaybillings** [comment]
Please double check your documentation as well.

**Comment by menghanli** [comment]
Hi Jay, I fixed the userMatDB.xml file and the documentations! You can double check when you get time. Thank you!

**Comment by jayjaybillings** [comment]
Thanks for fixing your changes! Sorry for the long time that it took for me to merge this change. I have accepted it since it passed the checks and was less than 1000 lines.

**Pull request merged**
