### PR TITLE
[470838]Correcting NekWriter to generic linebreaks

### PR DESCRIPTION
**Pull request by SmithRWORNL**
NewWriter has been changed to utilize system-agnostic linebreak
characters instead of hardcoded values for. Files created this way have
been confirmed to be formatted correctly under both Linux and Windows.

Bug: 470838 https://bugs.eclipse.org/bugs/show_bug.cgi?id=470838
Signed-off-by: Robert Smith <SmithRW@ornl.gov>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=470838

**Comment by jayjaybillings** [comment]
Accepted.

**Comment by arbennett** [comment]
You may wish to be careful on this one, Nek5000 is not designed to run on
Windows.  Generating a file on Windows then trying to run it with Nek might
cause issues.

On Fri, Jun 26, 2015 at 11:11 AM, Jay Jay Billings <notifications@github.com

**Comment by jayjaybillings** [comment]
We need to move this discussion to the bug report.

**Pull request merged**
