### PR TITLE
Add EMF model

### PR DESCRIPTION
**Pull request by anarak**

### CODE REVIEW

**Comment by amccaskey** [comment]
@anarak Couple of things that I see with this after a quick look: 

Looks like you also committed the bin directory in the plugin. Could you remove it?

And I don't see the tests bundle. Can you add commit it too?

**Comment by jayjaybillings** [comment]
@anarak You should add bin/ to .gitignore.

**Comment by anarak** [comment]
Added test bundle (including edit and editor) to the model and deleted bin directory from commit.

**Comment by amccaskey** [comment]
@anarak just tried to build this and got the following error
```bash
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.ice.caebat.batml 2.2.0.qualifier
[ERROR]   Missing requirement: org.eclipse.ice.item 2.2.0.qualifier requires 'package org.eclipse.eavp.viz.datastructures 0.0.0' but it could not be found
```

**Comment by amccaskey** [comment]
@anarak please get the build working and then we'll look into merging. I would also suggest that you merge the latest changes from next into your mccaskey/appstore branch.

**Comment by SmithRWORNL** [comment]
That looks related to the split package issue I fixed yesterday. Was that built with the latest version of next?

**Comment by amccaskey** [comment]
@SmithRWORNL don't think so - we just need a merge of latest from next into this branch on her fork

**Comment by anarak** [comment]
@amccaskey I created EMF model separately from the ICE and then just added it to ICE's repo for you to see the model. The reason for creating the model separately is when I imported Ecore tools to ICE, I had errors which I posted to Mattermost, so couldn't proceed with the model unless I created it as a separate project. 

Now, after merging latest next and mccaskey/appstore branches I have the following error similar to yours when building ICE:

```
[INFO] org.eclipse.ice.tests.core ......................... SUCCESS [  2.381 s]
[INFO] org.eclipse.ice.tests.datastructures ............... FAILURE [ 15.121 s]
[INFO] org.eclipse.ice.developer .......................... SKIPPED
```

The model can be opened and viewed despite these build errors though. I'll look into the errors and see what can be done.

**Comment by SmithRWORNL** [comment]
@anarak Have you downloaded the ICETests folder to the machine you're building on?

**Comment by anarak** [comment]
@SmithRWORNL I don't remember downloading ICETests folder nor ever had to.

**Comment by SmithRWORNL** [comment]
@anarak Did Jay ever give you access to the ICETests-private repo? I think that it's still required to get do the unit tests in the build.

**Comment by anarak** [comment]
@SmithRWORNL No, I don't have this access. I'll ask Jay.

**Comment by jayjaybillings** [comment]
Two things:
* ICE build instructions are [here](http://wiki.eclipse.org/ICE_Build_Instructions) and someone on the team should have already pointed you to them. They include a note on asking for the tests.
* The tests are no longer private. You can get them from [here](https://github.com/jayjaybillings/ICETests).

**Comment by jayjaybillings** [comment]
I should add: just check those tests out directly in your home directory with
```
git clone https://github.com/jayjaybillings/ICETests
```

**Comment by anarak** [comment]
The above commit passed the build.

**Comment by amccaskey** [comment]
All checks passed. Looks good, going to merge now.

**Pull request merged**
