### PR TITLE
JavaFX Geometry Editor Replacement + CLA fixes

### PR DESCRIPTION
**Pull request by enleeten**
Here is the new JavaFX geometry editor commit along with a few fixes for the build.

### CODE REVIEW

**Comment by amccaskey** [comment]
I can report that this builds on my Mac.

**Comment by jayjaybillings** [comment]
@SmithRWORNL Will you confirm that this builds on Linux and Windows please?

**Comment by SmithRWORNL** [comment]
?It builds on Windows, but I ran into problems actually running it. Alex and I are taking a look into that, and I'll check the Linux build in the meantime.

________________________________

**Comment by amccaskey** [comment]
Yea just ran the product on Mac, doesn't appear to work when I create a new Geometry Editor. Robert mentioned his guess was that the new javafx service plugins may not be added to the product.

**Comment by jayjaybillings** [comment]
@enleeten I have two questions.

1.) Will you please provide a description of the exact role of JCSG in this work?

I cannot merge this directly into the repository because JCSG is included. I will need to create a CQ for this and JCSG. So, if JCSG is not currently used but will be then we should drop it and add it back later. If it is used, then I will just do both CQs and we will have to wait for approval.

2. ) Is there a bugzilla ticket number for tracking this work?

@amccaskey Ok - we can fix that without issuing a new pull request.

**Comment by SmithRWORNL** [comment]
The new packages were missing from the product, but although I can add them, I can't force viz.service.geometry.javafx to auto-start because it is a fragment instead of a plug-in. This will prevent the geometry editor from working because the service won't be registered.

Eclpise is also giving errors about "Plugin execution not covered by lifecycle configuration", but these don't seem to be causing any problems for the build.

**Comment by enleeten** [comment]
Fragments are loaded automatically with their host, they can't be started (they get merged into the host plugin's classpath).

I will remove the jcsg bundle.

**Comment by enleeten** [comment]
@SmithRWORNL The service is in the geometry service bundle. The core geometry editor implementation consists of the model and associated Eclipse UI code (no JavaFX or other dependency). The JavaFX fragment then provides a full implementation for use in the 

JavaFX is extremely tedious to get working with Eclipse. Make sure you have the latest Java 8 jre/jdk (some older ones don't really work).

On Linux, you can't use GTK3 with JavaFX, so you have to set SWT_GTK3=0 before launching ICE. The IDE will crash hard if you are using GTK3. I believe I read Oracle laid off the guy working on the JavaFX interop, so it may be a limitation for the foreseeable future.

Let me know if you need any help getting it running.

**Comment by enleeten** [comment]
@jayjaybillings I will create an issue in Eclipse Bugzilla (I was mainly using our JIRA).

**Comment by enleeten** [comment]
@jayjaybillings The bug has been created: 479587

**Comment by enleeten** [comment]
@SmithRWORNL I will update the product to make launching more simple, sorry!

**Comment by SmithRWORNL** [comment]
@enleeten Since the service is in viz.service.geometry, it's already starting up automatically, so the product is actually fine as is. 

Here is the error I'm getting when I try to open a geometry editor in Windows. Any help figuring it out would be greatly appreciated.

14:40:51.165 [main] ERROR o.e.i.client.widgets.ICEGeometryPage - Error creating Geometry Canvas with Geometry Service.
java.lang.Exception: 
	at org.eclipse.ice.viz.service.geometry.GeometryCanvas.materializeViewer(GeometryCanvas.java:146) ~[na:na]
	at org.eclipse.ice.viz.service.geometry.GeometryCanvas.draw(GeometryCanvas.java:90) ~[na:na]
	at org.eclipse.ice.client.widgets.ICEGeometryPage.createFormContent(ICEGeometryPage.java:179) ~[na:na]
	at org.eclipse.ui.forms.editor.FormPage$1.run(FormPage.java:152) [org.eclipse.ui.forms_3.6.200.v20150506-2029.jar:na]
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.ui.forms.editor.FormPage.createPartControl(FormPage.java:150) [org.eclipse.ui.forms_3.6.200.v20150506-2029.jar:na]
	at org.eclipse.ui.forms.editor.FormEditor.pageChange(FormEditor.java:471) [org.eclipse.ui.forms_3.6.200.v20150506-2029.jar:na]
	at org.eclipse.ui.part.MultiPageEditorPart.setActivePage(MultiPageEditorPart.java:1102) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.forms.editor.FormEditor.setActivePage(FormEditor.java:603) [org.eclipse.ui.forms_3.6.200.v20150506-2029.jar:na]
	at org.eclipse.ui.forms.editor.SharedHeaderFormEditor.createPages(SharedHeaderFormEditor.java:103) [org.eclipse.ui.forms_3.6.200.v20150506-2029.jar:na]
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:363) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:341) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:898) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:879) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:121) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:345) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:264) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162) [org.eclipse.e4.core.contexts_1.4.0.v20150421-2214.jar:na]
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:104) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:73) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:55) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:971) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:640) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:746) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:717) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:711) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) [org.eclipse.equinox.common_3.7.0.v20150402-1709.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:695) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer.showTab(StackRenderer.java:1306) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.LazyStackRenderer$1.handleEvent(LazyStackRenderer.java:72) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40) [org.eclipse.e4.ui.services_1.2.0.v20150422-0725.jar:na]
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:186) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:145) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4761) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:211) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36) [org.eclipse.e4.ui.services_1.2.0.v20150422-0725.jar:na]
	at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:197) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39) [org.eclipse.equinox.event_1.3.100.v20140115-1647.jar:na]
	at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:85) [org.eclipse.e4.ui.services_1.2.0.v20150422-0725.jar:na]
	at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:59) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374) [org.eclipse.emf.common_2.11.0.v20150512-0501.jar:na]
	at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:171) [org.eclipse.e4.ui.model.workbench_1.1.100.v20150407-1430.jar:na]
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:494) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:458) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:724) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:396) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1166) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3234) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3149) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3131) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3126) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3090) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3071) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ice.client.widgets.EclipseFormWidget.display(EclipseFormWidget.java:222) [org.eclipse.ice.client.widgets/:na]
	at org.eclipse.ice.client.internal.Client.loadItem(Client.java:382) [org.eclipse.ice.client/:na]
	at org.eclipse.ice.client.internal.Client.loadAfterCreate(Client.java:337) [org.eclipse.ice.client/:na]
	at org.eclipse.ice.client.internal.Client.createItem(Client.java:297) [org.eclipse.ice.client/:na]
	at org.eclipse.ice.client.common.wizards.NewItemWizard.performFinish(NewItemWizard.java:132) [org.eclipse.ice.client/:na]
	at org.eclipse.ice.client.common.wizards.NewItemWizardPage$4.doubleClick(NewItemWizardPage.java:245) [org.eclipse.ice.client/:na]
	at org.eclipse.jface.viewers.StructuredViewer$1.run(StructuredViewer.java:832) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42) [org.eclipse.equinox.common_3.7.0.v20150402-1709.jar:na]
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer.fireDoubleClick(StructuredViewer.java:829) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer.handleDoubleSelect(StructuredViewer.java:1150) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.viewers.StructuredViewer$4.widgetDefaultSelected(StructuredViewer.java:1263) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.util.OpenStrategy.fireDefaultSelectionEvent(OpenStrategy.java:252) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.util.OpenStrategy.access$0(OpenStrategy.java:249) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:311) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:827) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.jface.window.Window.open(Window.java:803) [org.eclipse.jface_3.11.0.v20150602-1400.jar:na]
	at org.eclipse.ice.client.common.CreateItemHandler.execute(CreateItemHandler.java:49) [org.eclipse.ice.client/:na]
	at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:295) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:90) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234) [org.eclipse.e4.core.di_1.5.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132) [org.eclipse.e4.core.contexts_1.4.0.v20150421-2214.jar:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152) [org.eclipse.e4.core.commands_0.11.0.v20150422-0725.jar:na]
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:493) [org.eclipse.core.commands_3.7.0.v20150422-0725.jar:na]
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:486) [org.eclipse.core.commands_3.7.0.v20150422-0725.jar:na]
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210) [org.eclipse.e4.core.commands_0.11.0.v20150422-0725.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:799) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.handleWidgetSelection(HandledContributionItem.java:675) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.access$7(HandledContributionItem.java:659) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem$4.handleEvent(HandledContributionItem.java:592) [org.eclipse.e4.ui.workbench.renderers.swt_0.13.0.v20150603-0857.jar:na]
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769) [org.eclipse.swt.win32.win32.x86_64_3.104.0.v20150528-0211.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337) [org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar:na]
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018) [org.eclipse.e4.ui.workbench.swt_0.13.0.v20150504-0621.jar:na]
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156) [org.eclipse.e4.ui.workbench_1.3.0.v20150531-1948.jar:na]
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337) [org.eclipse.core.databinding.observable_1.5.0.v20150422-0725.jar:na]
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150) [org.eclipse.ui.workbench_3.107.0.v20150510-1732.jar:na]
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139) [org.eclipse.ui.ide.application_1.1.0.v20150422-0725.jar:na]
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196) [org.eclipse.equinox.app_1.3.300.v20150423-1356.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235) [org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488) [org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar:na]

Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
	at org.eclipse.ice.viz.service.geometry.GeometryCanvas.materializeViewer(GeometryCanvas.java:144) ~[na:na]
	... 136 common frames omitted

Caused by: java.lang.NoClassDefFoundError: javafx/embed/swt/FXCanvas
	at org.eclipse.ice.viz.service.geometry.viewer.factory.GeometryViewerFactory.createViewer(GeometryViewerFactory.java:35) ~[na:na]
	... 141 common frames omitted

Caused by: java.lang.ClassNotFoundException: javafx.embed.swt.FXCanvas cannot be found by org.eclipse.ice.viz.service.geometry_2.1.7.20150825
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439) ~[org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352) ~[org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344) ~[org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160) ~[org.eclipse.osgi_3.10.100.v20150529-1857.jar:na]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_45]
	... 142 common frames omitted

**Comment by enleeten** [comment]
@SmithRWORNL Try including this bundle: org.eclipse.fx.osgi

You may need to reload the target platform with the target in this pull request. There are new dependencies for the Eclipse, OSGi and JavaFX integration.

**Comment by SmithRWORNL** [comment]
@enleeten I tried reloading the target platform. For Windows, this removes the errors, but the Geometry Editor is still just a blank screen. In Linux, the target can't be resolved. I get the error message: 

An error occurred while configuring the installed items.
Preference node "http:_download.eclipse.org_tools_cdt_releases_8.7" has been removed
session context was:(profile=TARGET_DEFINITION:resource:/org.eclipse.ice.target.mars/mars.target, phase=org.eclipse.equinox.internal.p2engine.phases.Configure, operand=null --> [R]org.eclipse.cdt.feature.group 8.7.0.201506070905. action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.AddRepositoryAction).

**Comment by enleeten** [comment]
@SmithRWORNL I've update the product file to include the javafx feature and also the boot classpath argument for getting JavaFX working with OSGi. That should fix your Windows issue, if not let me know.

The linux issue is odd, I added the JavaFX Eclipse p2 repo but not CDT. Are you guys using an internal mirror? Reading the message, it almost sounds like workspace corruption. That said, I've had some weirdness with our internal p2 mirrors recently. Some kind of partial IU got into the eclipse.org p2 repos and it broke all my tycho builds.

I would try with a fresh workspace and see if the issue persists (or clear the PDE bundle state from .metadata).

**Comment by jayjaybillings** [comment]
I agree; the CDT issue is something else. Tony's work shouldn't have affected that. Most likely you have either a corrupted workspace or some similarly messed up thing.

CDT is a standard part of ICE's Product since both @amccaskey and I use it regularly for our physics projects. It normally works fine with no tweaking required. 

You might also check the configuration of your target. It could be that the operating system or something is not properly set.

**Comment by SmithRWORNL** [comment]
@enleeten The latest change doesn't fix the issue for Windows. The GeometryCanvas throws an exception "org.eclipse.ice.viz.service.geometry.viewer.factory.GeometryViewerFactory cannot be found by org.eclipse.ice.viz.service.geometry_2.1.7.2015082" on line 136. 

For Linux, I'm getting that same error even with normal ICE, including in different workspaces, so you two are right that it doesn't appear related to this pull request.

**Comment by jayjaybillings** [comment]
Seeing that all technical requirements have been met, I have submitted this code to the Eclipse Foundation for IP review. A Contribution Questionnaire for this work has been created:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10275

I will let you know the status of the review.

**Comment by SmithRWORNL** [comment]
There are several issues with the geometry editor which can be put in as bugs once the pull request is accepted.

* The Geometry Editor does not work on Windows, instead displaying a blank grey screen. I fixed this when launched from ICE by combining the viz.service.geometry and viz.service.geometry.javafx bundles and changing the GeometryCanvas's materialzeViewer() function's try block to simply return a new FXGeometryViewer, bypassing the factory. However, this caused the build to fail, so I can't confirm it would really fix the issue.
* The user should have the option to center the camera on the origin, manipulating the angle from which the origin will be viewed instead of using the keyboard to set the camera's position and using the the mouse to set which angle from that point the camera will point. Also, the camera tends to turn abruptly at the very beginning of a click and drag.
* There are issues with the geometry objects' clipping and position. This can be seen in the attached screenshots, in which the purple sphere is always behind the white cylinder, no matter what direction they are viewed from.
geometryeditorangle3
geometryeditorangle4
geometryeditorangle1
geometryeditorangle2
* Tube primitives should be cylinders with their centers empty, but instead are displayed as simple cylinders.
* When an item in the Shapes view is selected, the corresponding shape in the Geometry Editor should have a graphical indication that it is the part selected. For example, in the old Geometry Editor, this was shown by the shape turning red.

**Comment by jayjaybillings** [comment]
This work has been approved for check in by the Foundation under CQ 10275. I will merge it as soon as I have time.

@amccaskey or @SmithRWORNL, does this build for you?

**Comment by amccaskey** [comment]
Builds on my Mac.

**Comment by SmithRWORNL** [comment]
@jayjaybillings 
It builds under both Windows and Linux for me. However, the built binaries do not actually work. In both cases, I think we need to add in the equivalent of the -Dosgi.framework.extensions=org.eclipse.fx.osgi VM argument to the binary for the build to work with JavaFX. 

See my above comment for an additional fix needed for the Linux version and a fix for the Windows version that got the editor working but broke the build for me.

**Comment by amccaskey** [comment]
Builds, but running it does not work as expected on Mac, probably the same thing Robert found. Creating a new geometry editor item shows a blank gray composite and no JavaFX stuff. 
screen shot 2015-11-09 at 2 19 21 pm

**Comment by enleeten** [comment]
I will investigate this issue. There's no platform specific code, so it shouldn't really be an issue.

**Comment by jayjaybillings** [comment]
@SmithRWORNL Please create bug reports on all of these issues. 

@amccaskey Please create a separate branch (mccrary/javafx) and pull @enleeten 's code into it. We need to get this code committed and close the PR. Any other fixes from Tony can be tagged to one of the new bugs that @SmithRWORNL creates.

**Comment by jayjaybillings** [comment]
This has been pulled into its own branch, mccrary/javafx and @SmithRWORNL is working on merging it into his latest set of changes for the viz bundles. Hopefully we'll have this closed soon.

**Comment by jayjaybillings** [comment]
@SmithRWORNL has finished merging this into the @eclipse/eclipse-ice/UnifiedVizRefactor_noReactor branch and it will be pushed to next after he finishes addressing some build issues. Thanks @enleeten for the contribution and @SmithRWORNL for getting it integrated!

**Pull request closed without merging**
