### PR TITLE
Bug 481365 BasicComponentProvider and generic extension helper

### PR DESCRIPTION
**Pull request by nickstanish**
- Created a generic extension helper which will reduce repetitive code of finding extensions to an id and then casting the implementations.
- Added that extension helper to the existing providers
- Created BasicComponentProvider interface and extension point as well as default extension
- Fixed IResourcePageProvider extension point (was using "Class" instead of "class")

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=481365

**Comment by jayjaybillings** [comment]
Nick asked me to wait another hour or so before accepting this because he has one more small thing that he is fixing.

**Comment by nickstanish** [comment]
Ok @jayjaybillings it's ready

**Comment by jayjaybillings** [comment]
This addresses a bug and adds some awesome capabilities, passes the validation checks and is less than 1000 lines, so I am accepting it. Thanks very much @nickstanish!

**Pull request merged**
